# Generated by Django 4.2.7 on 2026-01-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_id_alter_chatmessage_id_alter_document_id'),
    ]

    operations = [
    ]
