# Generated by Django 4.2.7 on 2026-01-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_make_session_id_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
